image: docker:20.10

services:
  - name: docker:20.10-dind
    command: ["--tls=false"]


variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: "overlay2"
  SCALA_VERSION: "3.2.2-RC1"
  SBT_VERSION: "1.8.0"
  TESTCONTAINERS_RYUK_DISABLED: "true"

stages:
  - test
  - publish
  
before_script:

  - export PATH="/usr/local/sbt/bin:$PATH"
  - apk update 
  - apk add ca-certificates wget tar bash openjdk17-jdk git
  - mkdir -p "/usr/local/sbt" 
  - wget -qO - --no-check-certificate "https://github.com/sbt/sbt/releases/download/v$SBT_VERSION/sbt-$SBT_VERSION.tgz" | tar xz -C /usr/local/sbt --strip-components=1 
  - sbt sbtVersion
  #- docker info
  
test-coverage:
  stage: test
  script:
    - sbt cov
  artifacts:
    when: always
    reports:
      cobertura: target/scala-$SCALA_VERSION/coverage-report/cobertura.xml
  only:
    - master
    - tags
    - merge_requests
      
publish-docker:
  stage: publish
  script:
    - sbt docker:publishLocal
  only:
    - master
    - tags
