addSbtPlugin("com.typesafe.sbt" % "sbt-git" % "1.0.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.4.1")
addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.9")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.6.0")
lazy val root = project.in(file(".")).dependsOn(ghReleasePlugin)
lazy val ghReleasePlugin = RootProject(uri("https://github.com/hyst329/sbt-github-release.git"))
addSbtPlugin("org.wartremover" % "sbt-wartremover" % "2.4.2")